name: Test
on:
  workflow_dispatch:

  pull_request:
    types: [ opened, synchronize, reopened, closed ]
    branches:
      - main

jobs:
  black-flake8:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-python@v4
          with:
            python-version: "3.10"
        - name: Install dependencies
          run: python -m pip install tox
        - name: flake8
          run: python -m tox -e flake8
          continue-on-error: true
        - name: black
          run: python -m tox -e black

  mypy:
    needs: [black-flake8]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [ "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: python -m pip install tox
      - name: Run type-checking
        continue-on-error: true
        run: python -m tox -e mypy

  test-dev:
    needs: [black-flake8, mypy]
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-python@v4
          with:
            python-version: "3.10"
        - name: Install dependencies
          run: python -m pip install tox
        - name: Run dev env test
          run: python -m tox -e py310-req

  test:
    needs: [test-dev]
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        python-version: ["3.11"]
    runs-on: ${{ matrix.os}}

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: python -m pip install tox
      - name: Run tests
        run: tox -e py

  create-tag:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          output=$(python setup.py --version)
          echo "::set-output name=version::$output"
        id: version

      - name: Create tag
        if: github.event.pull_request.merged == true
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/v${{ steps.version.outputs.version }}",
              sha: context.sha
            })

  build-publish:
    needs: [ black-flake8, mypy, test ]
    name: Build and publish the package to TestPyPI
    if: github.event.pull_request.merged == true && github.event_name != 'schedule'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install twine
      - name: Build package
        run: python setup.py sdist bdist_wheel
      - name: Check the package
        run: twine check dist/*
      - name: Publish to PyPI
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run:
          twine upload --non-interactive dist/*
