name: Tests

on: [push]

jobs:
  test-dev:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-python@v4
          with:
            python-version: "3.11"
        - name: install tox
          run: pip install tox
        - name: run tox
          run: tox -e py