name: Tests
on:
  workflow_dispatch:

  pull_request:
    types: [ opened, synchronize, reopened, closed ]

  workflow_run:
    workflows: ["Linter"]
    types:
      - completed

jobs:
  test-dev:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-python@v4
          with:
            python-version: "3.11"
        - name: Install dependencies
          run: python -m pip install tox
        - name: Run dev env test
          run: python -m tox -e py-dev
        - name: Run unit tests
          run: python -m unittest discover tests/unit
        - name: Run integration tests
          run: python -m unittest discover tests/integration
        - name: Run connectivity tests
          run: python -m unittest discover tests/connectivity