name: Tests

on: [push]

jobs:
  test-dev:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-python@v4
          with:
            python-version: "3.11"
        - name: Install dependencies
          run: pip install tox
        - name: Run dev env test
          run: tox -e py
        - name: Run calculations tests
          run: unittest discover tests/calculations
        - name: Run integration tests
          run: unittest discover tests/integration
        - name: Run connectivity tests
          run: unittest discover tests/connectivity